// @generated by protoc-gen-es v1.7.2 with parameter "target=ts"
// @generated from file services/eczema/v1/api.proto (package services.eczema.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum services.eczema.v1.Location
 */
export enum Location {
  /**
   * @generated from enum value: SCALP_F = 0;
   */
  SCALP_F = 0,

  /**
   * @generated from enum value: SCALP_B = 1;
   */
  SCALP_B = 1,

  /**
   * @generated from enum value: SCALP_L = 2;
   */
  SCALP_L = 2,

  /**
   * @generated from enum value: SCALP_R = 3;
   */
  SCALP_R = 3,

  /**
   * @generated from enum value: FACE_LT = 4;
   */
  FACE_LT = 4,

  /**
   * @generated from enum value: FACE_RT = 5;
   */
  FACE_RT = 5,

  /**
   * @generated from enum value: EAR_LT = 6;
   */
  EAR_LT = 6,

  /**
   * @generated from enum value: EAR_LB = 7;
   */
  EAR_LB = 7,

  /**
   * @generated from enum value: EAR_RT = 8;
   */
  EAR_RT = 8,

  /**
   * @generated from enum value: EAR_RB = 9;
   */
  EAR_RB = 9,

  /**
   * @generated from enum value: NECK_FL = 10;
   */
  NECK_FL = 10,

  /**
   * @generated from enum value: NECK_FR = 11;
   */
  NECK_FR = 11,

  /**
   * @generated from enum value: NECK_BL = 12;
   */
  NECK_BL = 12,

  /**
   * @generated from enum value: NECK_BR = 13;
   */
  NECK_BR = 13,

  /**
   * @generated from enum value: SHOULDER_L = 14;
   */
  SHOULDER_L = 14,

  /**
   * @generated from enum value: SHOULDER_R = 15;
   */
  SHOULDER_R = 15,

  /**
   * @generated from enum value: ELBOW_LC = 16;
   */
  ELBOW_LC = 16,

  /**
   * @generated from enum value: ELBOW_RC = 17;
   */
  ELBOW_RC = 17,

  /**
   * @generated from enum value: ELBOW_L_UP = 18;
   */
  ELBOW_L_UP = 18,

  /**
   * @generated from enum value: ELBOW_R_UP = 19;
   */
  ELBOW_R_UP = 19,

  /**
   * @generated from enum value: CHEST_PEC_L = 20;
   */
  CHEST_PEC_L = 20,

  /**
   * @generated from enum value: CHEST_PEC_R = 21;
   */
  CHEST_PEC_R = 21,

  /**
   * @generated from enum value: CHEST_CENTER = 22;
   */
  CHEST_CENTER = 22,

  /**
   * @generated from enum value: BELLY_UP = 23;
   */
  BELLY_UP = 23,

  /**
   * @generated from enum value: BELLY_LO = 24;
   */
  BELLY_LO = 24,

  /**
   * @generated from enum value: TORSO_FL_UP = 25;
   */
  TORSO_FL_UP = 25,

  /**
   * @generated from enum value: TORSO_FL_LO = 26;
   */
  TORSO_FL_LO = 26,

  /**
   * @generated from enum value: TORSO_FR_UP = 27;
   */
  TORSO_FR_UP = 27,

  /**
   * @generated from enum value: TORSO_FR_LO = 28;
   */
  TORSO_FR_LO = 28,

  /**
   * @generated from enum value: TORSO_BL = 29;
   */
  TORSO_BL = 29,

  /**
   * @generated from enum value: TORSO_BR = 30;
   */
  TORSO_BR = 30,

  /**
   * @generated from enum value: BACK_TL = 31;
   */
  BACK_TL = 31,

  /**
   * @generated from enum value: BACK_TR = 32;
   */
  BACK_TR = 32,

  /**
   * @generated from enum value: WAIST_FL = 33;
   */
  WAIST_FL = 33,

  /**
   * @generated from enum value: WAIST_FR = 34;
   */
  WAIST_FR = 34,

  /**
   * @generated from enum value: WAIST_SL = 35;
   */
  WAIST_SL = 35,

  /**
   * @generated from enum value: WAIST_SR = 36;
   */
  WAIST_SR = 36,

  /**
   * @generated from enum value: CROTCH_FR = 37;
   */
  CROTCH_FR = 37,

  /**
   * @generated from enum value: CROTCH_FL = 38;
   */
  CROTCH_FL = 38,

  /**
   * @generated from enum value: CROTCH_B = 39;
   */
  CROTCH_B = 39,

  /**
   * @generated from enum value: BUTT_L = 40;
   */
  BUTT_L = 40,

  /**
   * @generated from enum value: BUTT_R = 41;
   */
  BUTT_R = 41,

  /**
   * @generated from enum value: THIGH_FL = 42;
   */
  THIGH_FL = 42,

  /**
   * @generated from enum value: THIGH_FR = 43;
   */
  THIGH_FR = 43,

  /**
   * @generated from enum value: THIGH_BL = 44;
   */
  THIGH_BL = 44,

  /**
   * @generated from enum value: THIGH_BR = 45;
   */
  THIGH_BR = 45,

  /**
   * @generated from enum value: THIGH_SL = 46;
   */
  THIGH_SL = 46,

  /**
   * @generated from enum value: THIGH_SR = 47;
   */
  THIGH_SR = 47,

  /**
   * @generated from enum value: KNEE_FL = 48;
   */
  KNEE_FL = 48,

  /**
   * @generated from enum value: KNEE_FR = 49;
   */
  KNEE_FR = 49,

  /**
   * @generated from enum value: KNEE_BL = 50;
   */
  KNEE_BL = 50,

  /**
   * @generated from enum value: KNEE_BR = 51;
   */
  KNEE_BR = 51,

  /**
   * @generated from enum value: KNEE_SL = 52;
   */
  KNEE_SL = 52,

  /**
   * @generated from enum value: KNEE_SR = 53;
   */
  KNEE_SR = 53,

  /**
   * @generated from enum value: LEG_FL = 54;
   */
  LEG_FL = 54,

  /**
   * @generated from enum value: LEG_BL = 55;
   */
  LEG_BL = 55,

  /**
   * @generated from enum value: LEG_FR = 56;
   */
  LEG_FR = 56,

  /**
   * @generated from enum value: LEG_BR = 57;
   */
  LEG_BR = 57,
}
// Retrieve enum metadata with: proto3.getEnumType(Location)
proto3.util.setEnumType(Location, "services.eczema.v1.Location", [
  { no: 0, name: "SCALP_F" },
  { no: 1, name: "SCALP_B" },
  { no: 2, name: "SCALP_L" },
  { no: 3, name: "SCALP_R" },
  { no: 4, name: "FACE_LT" },
  { no: 5, name: "FACE_RT" },
  { no: 6, name: "EAR_LT" },
  { no: 7, name: "EAR_LB" },
  { no: 8, name: "EAR_RT" },
  { no: 9, name: "EAR_RB" },
  { no: 10, name: "NECK_FL" },
  { no: 11, name: "NECK_FR" },
  { no: 12, name: "NECK_BL" },
  { no: 13, name: "NECK_BR" },
  { no: 14, name: "SHOULDER_L" },
  { no: 15, name: "SHOULDER_R" },
  { no: 16, name: "ELBOW_LC" },
  { no: 17, name: "ELBOW_RC" },
  { no: 18, name: "ELBOW_L_UP" },
  { no: 19, name: "ELBOW_R_UP" },
  { no: 20, name: "CHEST_PEC_L" },
  { no: 21, name: "CHEST_PEC_R" },
  { no: 22, name: "CHEST_CENTER" },
  { no: 23, name: "BELLY_UP" },
  { no: 24, name: "BELLY_LO" },
  { no: 25, name: "TORSO_FL_UP" },
  { no: 26, name: "TORSO_FL_LO" },
  { no: 27, name: "TORSO_FR_UP" },
  { no: 28, name: "TORSO_FR_LO" },
  { no: 29, name: "TORSO_BL" },
  { no: 30, name: "TORSO_BR" },
  { no: 31, name: "BACK_TL" },
  { no: 32, name: "BACK_TR" },
  { no: 33, name: "WAIST_FL" },
  { no: 34, name: "WAIST_FR" },
  { no: 35, name: "WAIST_SL" },
  { no: 36, name: "WAIST_SR" },
  { no: 37, name: "CROTCH_FR" },
  { no: 38, name: "CROTCH_FL" },
  { no: 39, name: "CROTCH_B" },
  { no: 40, name: "BUTT_L" },
  { no: 41, name: "BUTT_R" },
  { no: 42, name: "THIGH_FL" },
  { no: 43, name: "THIGH_FR" },
  { no: 44, name: "THIGH_BL" },
  { no: 45, name: "THIGH_BR" },
  { no: 46, name: "THIGH_SL" },
  { no: 47, name: "THIGH_SR" },
  { no: 48, name: "KNEE_FL" },
  { no: 49, name: "KNEE_FR" },
  { no: 50, name: "KNEE_BL" },
  { no: 51, name: "KNEE_BR" },
  { no: 52, name: "KNEE_SL" },
  { no: 53, name: "KNEE_SR" },
  { no: 54, name: "LEG_FL" },
  { no: 55, name: "LEG_BL" },
  { no: 56, name: "LEG_FR" },
  { no: 57, name: "LEG_BR" },
]);

/**
 * @generated from enum services.eczema.v1.Action
 */
export enum Action {
  /**
   * @generated from enum value: NOTHING = 0;
   */
  NOTHING = 0,

  /**
   * @generated from enum value: SCRATCH = 1;
   */
  SCRATCH = 1,

  /**
   * @generated from enum value: APPLY_LOTION = 2;
   */
  APPLY_LOTION = 2,

  /**
   * @generated from enum value: APPLY_STEROIDS = 3;
   */
  APPLY_STEROIDS = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(Action)
proto3.util.setEnumType(Action, "services.eczema.v1.Action", [
  { no: 0, name: "NOTHING" },
  { no: 1, name: "SCRATCH" },
  { no: 2, name: "APPLY_LOTION" },
  { no: 3, name: "APPLY_STEROIDS" },
]);

/**
 * @generated from enum services.eczema.v1.Variant
 */
export enum Variant {
  /**
   * @generated from enum value: SCALING = 0;
   */
  SCALING = 0,

  /**
   * @generated from enum value: DOTTING = 1;
   */
  DOTTING = 1,

  /**
   * @generated from enum value: SCALP = 2;
   */
  SCALP = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(Variant)
proto3.util.setEnumType(Variant, "services.eczema.v1.Variant", [
  { no: 0, name: "SCALING" },
  { no: 1, name: "DOTTING" },
  { no: 2, name: "SCALP" },
]);

/**
 * @generated from message services.eczema.v1.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from field: uint64 time = 1;
   */
  time = protoInt64.zero;

  /**
   * @generated from field: uint64 duration = 2;
   */
  duration = protoInt64.zero;

  /**
   * how bad the eczema is in that region right now
   * - 0 = completely clear
   * - 0.25 = minimal issues
   * - 0.5 = some issues
   * - 0.75 = significant issues
   * - 1 = in dire need of help
   *
   * @generated from field: float state = 3;
   */
  state = 0;

  /**
   * @generated from field: services.eczema.v1.Variant variant = 4;
   */
  variant = Variant.SCALING;

  /**
   * @generated from field: services.eczema.v1.Location location = 5;
   */
  location = Location.SCALP_F;

  /**
   * @generated from field: services.eczema.v1.Action action = 6;
   */
  action = Action.NOTHING;

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "services.eczema.v1.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "time", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "duration", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "state", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 4, name: "variant", kind: "enum", T: proto3.getEnumType(Variant) },
    { no: 5, name: "location", kind: "enum", T: proto3.getEnumType(Location) },
    { no: 6, name: "action", kind: "enum", T: proto3.getEnumType(Action) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

/**
 * Push
 *
 * @generated from message services.eczema.v1.PushRequest
 */
export class PushRequest extends Message<PushRequest> {
  /**
   * @generated from field: repeated services.eczema.v1.Event events = 1;
   */
  events: Event[] = [];

  constructor(data?: PartialMessage<PushRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "services.eczema.v1.PushRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushRequest {
    return new PushRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushRequest {
    return new PushRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushRequest {
    return new PushRequest().fromJsonString(jsonString, options);
  }

  static equals(a: PushRequest | PlainMessage<PushRequest> | undefined, b: PushRequest | PlainMessage<PushRequest> | undefined): boolean {
    return proto3.util.equals(PushRequest, a, b);
  }
}

/**
 * @generated from message services.eczema.v1.PushResponse
 */
export class PushResponse extends Message<PushResponse> {
  constructor(data?: PartialMessage<PushResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "services.eczema.v1.PushResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushResponse {
    return new PushResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushResponse {
    return new PushResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushResponse {
    return new PushResponse().fromJsonString(jsonString, options);
  }

  static equals(a: PushResponse | PlainMessage<PushResponse> | undefined, b: PushResponse | PlainMessage<PushResponse> | undefined): boolean {
    return proto3.util.equals(PushResponse, a, b);
  }
}

