// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file services/eczema/v1/api.proto (package services.eczema.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file services/eczema/v1/api.proto.
 */
export const file_services_eczema_v1_api: GenFile = /*@__PURE__*/
  fileDesc("ChxzZXJ2aWNlcy9lY3plbWEvdjEvYXBpLnByb3RvEhJzZXJ2aWNlcy5lY3plbWEudjEiwAEKBUV2ZW50EgwKBHRpbWUYASABKAQSEAoIZHVyYXRpb24YAiABKAQSDQoFc3RhdGUYAyABKAISLAoHdmFyaWFudBgEIAEoDjIbLnNlcnZpY2VzLmVjemVtYS52MS5WYXJpYW50Ei4KCGxvY2F0aW9uGAUgASgOMhwuc2VydmljZXMuZWN6ZW1hLnYxLkxvY2F0aW9uEioKBmFjdGlvbhgGIAEoDjIaLnNlcnZpY2VzLmVjemVtYS52MS5BY3Rpb24iOAoLUHVzaFJlcXVlc3QSKQoGZXZlbnRzGAEgAygLMhkuc2VydmljZXMuZWN6ZW1hLnYxLkV2ZW50Ig4KDFB1c2hSZXNwb25zZSqwBgoITG9jYXRpb24SCwoHU0NBTFBfRhAAEgsKB1NDQUxQX0IQARILCgdTQ0FMUF9MEAISCwoHU0NBTFBfUhADEgsKB0ZBQ0VfTFQQBBILCgdGQUNFX1JUEAUSCgoGRUFSX0xUEAYSCgoGRUFSX0xCEAcSCgoGRUFSX1JUEAgSCgoGRUFSX1JCEAkSCwoHTkVDS19GTBAKEgsKB05FQ0tfRlIQCxILCgdORUNLX0JMEAwSCwoHTkVDS19CUhANEg4KClNIT1VMREVSX0wQDhIOCgpTSE9VTERFUl9SEA8SDAoIRUxCT1dfTEMQEBIMCghFTEJPV19SQxAREg4KCkVMQk9XX0xfVVAQEhIOCgpFTEJPV19SX1VQEBMSDwoLQ0hFU1RfUEVDX0wQFBIPCgtDSEVTVF9QRUNfUhAVEhAKDENIRVNUX0NFTlRFUhAWEgwKCEJFTExZX1VQEBcSDAoIQkVMTFlfTE8QGBIPCgtUT1JTT19GTF9VUBAZEg8KC1RPUlNPX0ZMX0xPEBoSDwoLVE9SU09fRlJfVVAQGxIPCgtUT1JTT19GUl9MTxAcEgwKCFRPUlNPX0JMEB0SDAoIVE9SU09fQlIQHhILCgdCQUNLX1RMEB8SCwoHQkFDS19UUhAgEgwKCFdBSVNUX0ZMECESDAoIV0FJU1RfRlIQIhIMCghXQUlTVF9TTBAjEgwKCFdBSVNUX1NSECQSDQoJQ1JPVENIX0ZSECUSDQoJQ1JPVENIX0ZMECYSDAoIQ1JPVENIX0IQJxIKCgZCVVRUX0wQKBIKCgZCVVRUX1IQKRIMCghUSElHSF9GTBAqEgwKCFRISUdIX0ZSECsSDAoIVEhJR0hfQkwQLBIMCghUSElHSF9CUhAtEgwKCFRISUdIX1NMEC4SDAoIVEhJR0hfU1IQLxILCgdLTkVFX0ZMEDASCwoHS05FRV9GUhAxEgsKB0tORUVfQkwQMhILCgdLTkVFX0JSEDMSCwoHS05FRV9TTBA0EgsKB0tORUVfU1IQNRIKCgZMRUdfRkwQNhIKCgZMRUdfQkwQNxIKCgZMRUdfRlIQOBIKCgZMRUdfQlIQOSpICgZBY3Rpb24SCwoHTk9USElORxAAEgsKB1NDUkFUQ0gQARIQCgxBUFBMWV9MT1RJT04QAhISCg5BUFBMWV9TVEVST0lEUxADKi4KB1ZhcmlhbnQSCwoHU0NBTElORxAAEgsKB0RPVFRJTkcQARIJCgVTQ0FMUBACMloKDUVjemVtYVNlcnZpY2USSQoEUHVzaBIfLnNlcnZpY2VzLmVjemVtYS52MS5QdXNoUmVxdWVzdBogLnNlcnZpY2VzLmVjemVtYS52MS5QdXNoUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message services.eczema.v1.Event
 */
export type Event = Message<"services.eczema.v1.Event"> & {
  /**
   * @generated from field: uint64 time = 1;
   */
  time: bigint;

  /**
   * @generated from field: uint64 duration = 2;
   */
  duration: bigint;

  /**
   * how bad the eczema is in that region right now
   * - 0 = completely clear
   * - 0.25 = minimal issues
   * - 0.5 = some issues
   * - 0.75 = significant issues
   * - 1 = in dire need of help
   *
   * @generated from field: float state = 3;
   */
  state: number;

  /**
   * @generated from field: services.eczema.v1.Variant variant = 4;
   */
  variant: Variant;

  /**
   * @generated from field: services.eczema.v1.Location location = 5;
   */
  location: Location;

  /**
   * @generated from field: services.eczema.v1.Action action = 6;
   */
  action: Action;
};

/**
 * Describes the message services.eczema.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_services_eczema_v1_api, 0);

/**
 * Push
 *
 * @generated from message services.eczema.v1.PushRequest
 */
export type PushRequest = Message<"services.eczema.v1.PushRequest"> & {
  /**
   * @generated from field: repeated services.eczema.v1.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message services.eczema.v1.PushRequest.
 * Use `create(PushRequestSchema)` to create a new message.
 */
export const PushRequestSchema: GenMessage<PushRequest> = /*@__PURE__*/
  messageDesc(file_services_eczema_v1_api, 1);

/**
 * @generated from message services.eczema.v1.PushResponse
 */
export type PushResponse = Message<"services.eczema.v1.PushResponse"> & {
};

/**
 * Describes the message services.eczema.v1.PushResponse.
 * Use `create(PushResponseSchema)` to create a new message.
 */
export const PushResponseSchema: GenMessage<PushResponse> = /*@__PURE__*/
  messageDesc(file_services_eczema_v1_api, 2);

/**
 * @generated from enum services.eczema.v1.Location
 */
export enum Location {
  /**
   * @generated from enum value: SCALP_F = 0;
   */
  SCALP_F = 0,

  /**
   * @generated from enum value: SCALP_B = 1;
   */
  SCALP_B = 1,

  /**
   * @generated from enum value: SCALP_L = 2;
   */
  SCALP_L = 2,

  /**
   * @generated from enum value: SCALP_R = 3;
   */
  SCALP_R = 3,

  /**
   * @generated from enum value: FACE_LT = 4;
   */
  FACE_LT = 4,

  /**
   * @generated from enum value: FACE_RT = 5;
   */
  FACE_RT = 5,

  /**
   * @generated from enum value: EAR_LT = 6;
   */
  EAR_LT = 6,

  /**
   * @generated from enum value: EAR_LB = 7;
   */
  EAR_LB = 7,

  /**
   * @generated from enum value: EAR_RT = 8;
   */
  EAR_RT = 8,

  /**
   * @generated from enum value: EAR_RB = 9;
   */
  EAR_RB = 9,

  /**
   * @generated from enum value: NECK_FL = 10;
   */
  NECK_FL = 10,

  /**
   * @generated from enum value: NECK_FR = 11;
   */
  NECK_FR = 11,

  /**
   * @generated from enum value: NECK_BL = 12;
   */
  NECK_BL = 12,

  /**
   * @generated from enum value: NECK_BR = 13;
   */
  NECK_BR = 13,

  /**
   * @generated from enum value: SHOULDER_L = 14;
   */
  SHOULDER_L = 14,

  /**
   * @generated from enum value: SHOULDER_R = 15;
   */
  SHOULDER_R = 15,

  /**
   * @generated from enum value: ELBOW_LC = 16;
   */
  ELBOW_LC = 16,

  /**
   * @generated from enum value: ELBOW_RC = 17;
   */
  ELBOW_RC = 17,

  /**
   * @generated from enum value: ELBOW_L_UP = 18;
   */
  ELBOW_L_UP = 18,

  /**
   * @generated from enum value: ELBOW_R_UP = 19;
   */
  ELBOW_R_UP = 19,

  /**
   * @generated from enum value: CHEST_PEC_L = 20;
   */
  CHEST_PEC_L = 20,

  /**
   * @generated from enum value: CHEST_PEC_R = 21;
   */
  CHEST_PEC_R = 21,

  /**
   * @generated from enum value: CHEST_CENTER = 22;
   */
  CHEST_CENTER = 22,

  /**
   * @generated from enum value: BELLY_UP = 23;
   */
  BELLY_UP = 23,

  /**
   * @generated from enum value: BELLY_LO = 24;
   */
  BELLY_LO = 24,

  /**
   * @generated from enum value: TORSO_FL_UP = 25;
   */
  TORSO_FL_UP = 25,

  /**
   * @generated from enum value: TORSO_FL_LO = 26;
   */
  TORSO_FL_LO = 26,

  /**
   * @generated from enum value: TORSO_FR_UP = 27;
   */
  TORSO_FR_UP = 27,

  /**
   * @generated from enum value: TORSO_FR_LO = 28;
   */
  TORSO_FR_LO = 28,

  /**
   * @generated from enum value: TORSO_BL = 29;
   */
  TORSO_BL = 29,

  /**
   * @generated from enum value: TORSO_BR = 30;
   */
  TORSO_BR = 30,

  /**
   * @generated from enum value: BACK_TL = 31;
   */
  BACK_TL = 31,

  /**
   * @generated from enum value: BACK_TR = 32;
   */
  BACK_TR = 32,

  /**
   * @generated from enum value: WAIST_FL = 33;
   */
  WAIST_FL = 33,

  /**
   * @generated from enum value: WAIST_FR = 34;
   */
  WAIST_FR = 34,

  /**
   * @generated from enum value: WAIST_SL = 35;
   */
  WAIST_SL = 35,

  /**
   * @generated from enum value: WAIST_SR = 36;
   */
  WAIST_SR = 36,

  /**
   * @generated from enum value: CROTCH_FR = 37;
   */
  CROTCH_FR = 37,

  /**
   * @generated from enum value: CROTCH_FL = 38;
   */
  CROTCH_FL = 38,

  /**
   * @generated from enum value: CROTCH_B = 39;
   */
  CROTCH_B = 39,

  /**
   * @generated from enum value: BUTT_L = 40;
   */
  BUTT_L = 40,

  /**
   * @generated from enum value: BUTT_R = 41;
   */
  BUTT_R = 41,

  /**
   * @generated from enum value: THIGH_FL = 42;
   */
  THIGH_FL = 42,

  /**
   * @generated from enum value: THIGH_FR = 43;
   */
  THIGH_FR = 43,

  /**
   * @generated from enum value: THIGH_BL = 44;
   */
  THIGH_BL = 44,

  /**
   * @generated from enum value: THIGH_BR = 45;
   */
  THIGH_BR = 45,

  /**
   * @generated from enum value: THIGH_SL = 46;
   */
  THIGH_SL = 46,

  /**
   * @generated from enum value: THIGH_SR = 47;
   */
  THIGH_SR = 47,

  /**
   * @generated from enum value: KNEE_FL = 48;
   */
  KNEE_FL = 48,

  /**
   * @generated from enum value: KNEE_FR = 49;
   */
  KNEE_FR = 49,

  /**
   * @generated from enum value: KNEE_BL = 50;
   */
  KNEE_BL = 50,

  /**
   * @generated from enum value: KNEE_BR = 51;
   */
  KNEE_BR = 51,

  /**
   * @generated from enum value: KNEE_SL = 52;
   */
  KNEE_SL = 52,

  /**
   * @generated from enum value: KNEE_SR = 53;
   */
  KNEE_SR = 53,

  /**
   * @generated from enum value: LEG_FL = 54;
   */
  LEG_FL = 54,

  /**
   * @generated from enum value: LEG_BL = 55;
   */
  LEG_BL = 55,

  /**
   * @generated from enum value: LEG_FR = 56;
   */
  LEG_FR = 56,

  /**
   * @generated from enum value: LEG_BR = 57;
   */
  LEG_BR = 57,
}

/**
 * Describes the enum services.eczema.v1.Location.
 */
export const LocationSchema: GenEnum<Location> = /*@__PURE__*/
  enumDesc(file_services_eczema_v1_api, 0);

/**
 * @generated from enum services.eczema.v1.Action
 */
export enum Action {
  /**
   * @generated from enum value: NOTHING = 0;
   */
  NOTHING = 0,

  /**
   * @generated from enum value: SCRATCH = 1;
   */
  SCRATCH = 1,

  /**
   * @generated from enum value: APPLY_LOTION = 2;
   */
  APPLY_LOTION = 2,

  /**
   * @generated from enum value: APPLY_STEROIDS = 3;
   */
  APPLY_STEROIDS = 3,
}

/**
 * Describes the enum services.eczema.v1.Action.
 */
export const ActionSchema: GenEnum<Action> = /*@__PURE__*/
  enumDesc(file_services_eczema_v1_api, 1);

/**
 * @generated from enum services.eczema.v1.Variant
 */
export enum Variant {
  /**
   * @generated from enum value: SCALING = 0;
   */
  SCALING = 0,

  /**
   * @generated from enum value: DOTTING = 1;
   */
  DOTTING = 1,

  /**
   * @generated from enum value: SCALP = 2;
   */
  SCALP = 2,
}

/**
 * Describes the enum services.eczema.v1.Variant.
 */
export const VariantSchema: GenEnum<Variant> = /*@__PURE__*/
  enumDesc(file_services_eczema_v1_api, 2);

/**
 * @generated from service services.eczema.v1.EczemaService
 */
export const EczemaService: GenService<{
  /**
   * @generated from rpc services.eczema.v1.EczemaService.Push
   */
  push: {
    methodKind: "unary";
    input: typeof PushRequestSchema;
    output: typeof PushResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_services_eczema_v1_api, 0);

