// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file services/eczema/v1/api.proto (package services.eczema.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PushRequest, PushResponse } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service services.eczema.v1.EczemaService
 */
export const EczemaService = {
  typeName: "services.eczema.v1.EczemaService",
  methods: {
    /**
     * @generated from rpc services.eczema.v1.EczemaService.Push
     */
    push: {
      name: "Push",
      I: PushRequest,
      O: PushResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

