// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package eczemadb

type Event struct {
	Time     int64
	Duration int64
	State    float64
	Variant  int64
	Location int64
	Action   int64
}
